# Generated by Django 3.1.2 on 2020-11-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='sex',
            field=models.CharField(default='Male', max_length=50),
        ),
    ]
