# Generated by Django 3.1.2 on 2020-11-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='test5', max_length=100),
            preserve_default=False,
        ),
    ]
