# Generated by Django 3.1.2 on 2020-10-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='image/')),
                ('price', models.IntegerField(default=0)),
                ('seller', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(max_length=200)),
            ],
        ),
    ]
