# Generated by Django 3.1.2 on 2020-10-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_clothes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clotheslist',
            name='url',
        ),
    ]
