# Generated by Django 3.1.2 on 2020-10-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_clothes_app', '0002_remove_clotheslist_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clotheslist',
            name='amount',
        ),
    ]
