# Generated by Django 3.1.2 on 2020-10-29 21:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_clothes_app', '0003_remove_clotheslist_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clotheslist',
            name='comment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=['Pohan: good', 'Sharon: great']), blank=True, default=['Pohan: good', 'Sharon: great'], size=None),
            preserve_default=False,
        ),
    ]
