# Generated by Django 3.1.2 on 2020-10-29 21:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_clothes_app', '0004_clotheslist_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clotheslist',
            name='comment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None),
        ),
    ]
