# Generated by Django 3.1.2 on 2020-10-30 21:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_hand_clothes_app', '0005_auto_20201029_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clotheslist',
            name='comment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, size=None),
        ),
    ]
