# Generated by Django 3.1.2 on 2020-11-28 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('second_hand_clothes_app', '0006_auto_20201030_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='clotheslist',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
